version: '3.9'
services:
    nginx:
        build : requirements/nginx/.
        ports:
            - '80:80'
        volumes:
            - WordPress:/var/www/html/
        depends_on:
            - wordpress
        restart: always
    mariadb:
        build: requirements/mariadb/.
        ports:
            - '3306:3306'
        volumes:
            - DB:/var/lib/mysql
        restart: always
    wordpress:
        build: requirements/WordPress/.
        ports:
            - '9000:9000'
        volumes:
            - WordPress:/var/www/html/
        depends_on:
            - mariadb
        restart: always
volumes:
    WordPress:
        name : WordPress
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ~/goinfre/home/login/data/WordPress
    DB:
        name : DB
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ~/goinfre/home/login/data/DB
    # phpmyadmin:
    #     build: requirements/phpmyadmin/.
    #     ports:
    #         - '9000:9000'
    #     volumes:
    #         - WordPress:/var/www/html/
    #     links:
    #         - mariadb
    #     restart: always
    # adminer:
    #     build: requirements/adminer/.
    #     ports:
    #         - '9000:9000'
    #     volumes:
    #         - WordPress:/var/www/html/
    #     links:
    #         - mariadb
    #     restart: always
    # ftp:
    #     build: requirements/adminer/.
    #     ports:
    #         - '9000:9000'
    #     volumes:
    #         - WordPress:/var/www/html/
    #     links:
    #         - mariadb
    #     restart: always
    # site:
    #     build: requirements/adminer/.
    #     ports:
    #         - '9000:9000'
    #     volumes:
    #         - WordPress:/var/www/html/
    #     links:
    #         - mariadb
    #     restart: always
